# Generated by Django 5.1.2 on 2024-10-20 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('describtion', models.TextField(null=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branche_dept', to='company.branches')),
            ],
        ),
    ]
