# Generated by Django 5.1.2 on 2024-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_branches_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='describtion',
            field=models.TextField(help_text='write describtion about the deparment. ', null=True),
        ),
    ]
