# Generated by Django 5.1.2 on 2024-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_departments_describtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='describtion',
            field=models.TextField(help_text='write describtion about the deparment.', null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
